AWSTemplateFormatVersion: '2010-09-09'
Description: 'Locust Load Testing Cluster on AWS EC2'

Parameters:
  InstanceTypeMaster:
    Type: String
    Default: t3.medium
    Description: EC2 instance type for Locust master
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
  
  InstanceTypeWorker:
    Type: String
    Default: t3.small
    Description: EC2 instance type for Locust workers
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
  
  WorkerCount:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 5
    Description: Number of worker instances
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair name for SSH access
  
  AllowedCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to access Locust web UI

Conditions:
  HasWorker1: !Or [!Equals [!Ref WorkerCount, 1], !Equals [!Ref WorkerCount, 2], !Equals [!Ref WorkerCount, 3], !Equals [!Ref WorkerCount, 4], !Equals [!Ref WorkerCount, 5]]
  HasWorker2: !Or [!Equals [!Ref WorkerCount, 2], !Equals [!Ref WorkerCount, 3], !Equals [!Ref WorkerCount, 4], !Equals [!Ref WorkerCount, 5]]
  HasWorker3: !Or [!Equals [!Ref WorkerCount, 3], !Equals [!Ref WorkerCount, 4], !Equals [!Ref WorkerCount, 5]]
  HasWorker4: !Or [!Equals [!Ref WorkerCount, 4], !Equals [!Ref WorkerCount, 5]]
  HasWorker5: !Equals [!Ref WorkerCount, 5]

Resources:
  LocustSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Locust load testing cluster
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8089
          ToPort: 8089
          CidrIp: !Ref AllowedCIDR
          Description: Locust web UI
        - IpProtocol: tcp
          FromPort: 5557
          ToPort: 5557
          CidrIp: 10.0.0.0/8
          Description: Locust master-worker communication
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
          Description: SSH access

  LocustMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 - us-east-1. Update for your region!
      InstanceType: !Ref InstanceTypeMaster
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-master
        - Key: Purpose
          Value: load-testing

  LocustWorker1:
    Type: AWS::EC2::Instance
    Condition: HasWorker1
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: !Ref InstanceTypeWorker
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-worker-1
        - Key: Purpose
          Value: load-testing

  LocustWorker2:
    Type: AWS::EC2::Instance
    Condition: HasWorker2
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: !Ref InstanceTypeWorker
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-worker-2
        - Key: Purpose
          Value: load-testing

  LocustWorker3:
    Type: AWS::EC2::Instance
    Condition: HasWorker3
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: !Ref InstanceTypeWorker
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-worker-3
        - Key: Purpose
          Value: load-testing

  LocustWorker4:
    Type: AWS::EC2::Instance
    Condition: HasWorker4
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: !Ref InstanceTypeWorker
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-worker-4
        - Key: Purpose
          Value: load-testing

  LocustWorker5:
    Type: AWS::EC2::Instance
    Condition: HasWorker5
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: !Ref InstanceTypeWorker
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref LocustSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          pip3 install locust pyyaml python-dotenv requests boto3
          mkdir -p /home/ec2-user/chatbot-performance-testing
          cd /home/ec2-user/chatbot-performance-testing
      Tags:
        - Key: Name
          Value: locust-worker-5
        - Key: Purpose
          Value: load-testing

Outputs:
  MasterPublicIP:
    Description: Public IP address of Locust master
    Value: !GetAtt LocustMasterInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-MasterIP'
  
  MasterPrivateIP:
    Description: Private IP address of Locust master
    Value: !GetAtt LocustMasterInstance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-MasterPrivateIP'
  
  LocustWebUI:
    Description: URL to access Locust web UI
    Value: !Sub 'http://${LocustMasterInstance.PublicIp}:8089'
  
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref LocustSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroup'
